### PR TITLE
Fix: fix course labels

### LINKED ISSUE #138: Fix course labels
Define course labels according to the following principles:
- 2 weeks before and after the start of the course - 'available';
- start in the next 3 months as soon as it begins - 'upcoming';
- everything else is 'planned'.

Image

### PR DESCRIPTION
**Pull request by natanchik**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Course labels are defined according to the following principles:

- 2 weeks before and after the start of the course - 'available';
- start in the next 3 months as soon as it begins - 'upcoming';
- everything else is 'planned'.

## Related Tickets & Documents

- Related Issue #138
- Closes #138

## Screenshots, Recordings

Screenshot 2024-04-23 183451

Screenshot 2024-04-24 133440

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

File: src/features/course-main/course-main.tsx [hunk 1]
```diff
@@ -25,7 +28,11 @@ export const CourseMain = ({ courseName, type }: CourseMainProps) => {
   const requiredDate = new Date(course.startDate).setHours(0, 0, 0, 0);
```
Comment (ansivgit) [inline src/features/course-main/course-main.tsx:28]: I suggest to add some work-with-date library to make the code more readable

File: src/features/course-main/course-main.tsx [hunk 2]
```diff
@@ -10,6 +10,9 @@ interface CourseMainProps {
   type?: CourseType;
 }
 
+const MS_IN_2_WEEKS = 1209600000;
```
Comment (ansivgit) [inline src/features/course-main/course-main.tsx:13]: If we wouldn't like to use work-with-date library I suggest to create some function which takes `period-type` (month, day, week) and `periods-value` and returns value in ms

File: src/features/course-main/course-main.test.tsx [hunk 3]
```diff
@@ -73,3 +60,22 @@ describe('CourseMain', () => {
...
+          month: 'long',
+          day: 'numeric',
+        }),
+      },
+    });
+    render(<CourseMain courseName="Node.js course" type="Mentoring Program" />);
+    const labelElement = screen.getByText('available');
+    expect(labelElement).toBeVisible();
+  });
+});
```
Comment (Quiddlee) [inline src/features/course-main/course-main.test.tsx:81]: Maybe we should add more test cases to test also 'upcoming' courses

File: src/features/course-main/course-main.tsx [hunk 4]
```diff
@@ -25,7 +28,11 @@ export const CourseMain = ({ courseName, type }: CourseMainProps) => {
   const requiredDate = new Date(course.startDate).setHours(0, 0, 0, 0);
 
   const label =
-    requiredDate < now ? 'upcoming' : hasDayInDate(course.startDate) ? 'available' : 'planned';
+    hasDayInDate(course.startDate) && Math.abs(now - requiredDate) < MS_IN_2_WEEKS
+      ? 'available'
+      : now < requiredDate && requiredDate - now < MS_IN_3_MONTHS
+        ? 'upcoming'
+        : 'planned';
```
Comment (Quiddlee) [inline src/features/course-main/course-main.tsx:35]: I suggest

```typescript
  const todayDate = new Date().setHours(0, 0, 0, 0);
  const courseStartDate = new Date(course.startDate).setHours(0, 0, 0, 0);
  const msPassedSinceStart = todayDate - courseStartDate;
  const msLeftBeforeStart = courseStartDate - todayDate;

  const isCourseStarted = todayDate >= courseStartDate;
  const isAvailable =
    hasDayInDate(course.startDate) && isCourseStarted && msPassedSinceStart < MS_IN_2_WEEKS;
  const isUpcoming = !isCourseStarted && msLeftBeforeStart < MS_IN_3_MONTHS;
  let label = 'planned';

  if (isAvailable) {
    label = 'available';
  }

  if (isUpcoming) {
    label = 'upcoming';
  }

```

**Review by Quiddlee — CHANGES_REQUESTED** [review]

File: src/features/course-main/course-main.test.tsx (hunk 3 above)
Comment (natanchik) [reply src/features/course-main/course-main.test.tsx]: Done

File: src/features/course-main/course-main.tsx (hunk 1 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx]: Added date library Day.js

File: src/features/course-main/course-main.tsx (hunk 2 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx]: Added date library Day.js

File: src/features/course-main/course-main.tsx (hunk 4 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx]: Done

File: src/app/services/dayjs/index.ts [hunk 5]
```diff
@@ -0,0 +1,7 @@
+/* eslint-disable import/no-named-as-default-member */
```
Comment (Quiddlee) [inline src/app/services/dayjs/index.ts:1]: eslint disable comment could be removed, if you change code like that:

```tsx
import dayjs, { extend } from 'dayjs';
import isBetween from 'dayjs/plugin/isBetween';

extend(isBetween);

export const dayJS = dayjs;
```

Also, why do you re-export `dayjs`, with changed name?

File: src/features/course-main/course-main.test.tsx [hunk 6]
```diff
@@ -73,3 +62,33 @@ describe('CourseMain', () => {
...
+      course: {
+        ...testCourse.course,
+        startDate: dayJS().add(1, 'month').format('D MMM, YYYY'),
+      },
+    });
+    render(<CourseMain courseName="Node.js course" type="Mentoring Program" />);
+    const labelElement = screen.getByText(Labels.UPCOMING);
+    expect(labelElement).toBeVisible();
+  });
+});
```
Comment (Quiddlee) [inline src/features/course-main/course-main.test.tsx:94]: Good job!

File: src/features/course-main/course-main.tsx [hunk 7]
```diff
@@ -1,10 +1,11 @@
+import dayjs from 'dayjs';
```
Comment (Quiddlee) [inline src/features/course-main/course-main.tsx:1]: You have re-exported `dayjs` as `dayJS` but using the `dayjs` from the library itself, probably re-export could be removed

Comment (Quiddlee) [reply src/features/course-main/course-main.tsx:1]: I see that the tests are droped if you remove `dayJS` re-export. It could be fixed if you extend `isBetween` plugin in the `setup-test.ts` file. 

But in this case i don't really like the fact that we need to duplicate `extend` in 2 places if we want to add new plugin, so it's up to you, you can ignore my suggestion

image

File: src/app/services/dayjs/index.ts (hunk 5 above)
Comment (natanchik) [reply src/app/services/dayjs/index.ts]: Done

File: src/features/course-main/course-main.test.tsx (hunk 6 above)
Comment (natanchik) [reply src/features/course-main/course-main.test.tsx]: To avoid unnecessary renders by beforeEach. But I removed last Describe

File: src/features/course-main/course-main.tsx (hunk 7 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx:1]: I assume there will be additions of other plugins as well, so I'd prefer to keep the extensions in one place, but thanks for suggestion

**Review by Quiddlee — APPROVED** [review]

**Review by Quiddlee — APPROVED** [review]

File: src/features/course-main/course-main.tsx [hunk 8]
```diff
@@ -22,27 +23,35 @@ export const CourseMain = ({ courseName, type }: CourseMainProps) => {
...
+
+  let label = Labels.PLANNED;
+
+  if (isAvailable) {
+    label = Labels.AVAILABLE;
+  }
+
+  if (isUpcoming) {
+    label = Labels.UPCOMING;
+  }
```
Comment (SpaNb4) [inline src/features/course-main/course-main.tsx:44]: I'd extract it into a function outside the component

File: src/app/services/dayjs/index.ts [hunk 9]
```diff
@@ -0,0 +1,6 @@
+import dayjs, { extend } from 'dayjs';
+import isBetween from 'dayjs/plugin/isBetween';
+
+extend(isBetween);
+
+export const dayJS = dayjs;
```
Comment (SpaNb4) [inline src/app/services/dayjs/index.ts:6]: Do we really need to export this?

Comment (natanchik) [reply src/app/services/dayjs/index.ts:6]: It's because of the tests.

File: src/features/course-main/course-main.tsx
[the remark this answers is not in the document]
Comment (natanchik) [reply src/features/course-main/course-main.tsx:1]: Fixed

File: src/features/course-main/course-main.tsx (hunk 8 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx]: Done

File: src/app/types/labels.types.ts [hunk 10]
```diff
@@ -0,0 +1,5 @@
+export enum Labels {
```
Comment (SpaNb4) [inline src/app/types/labels.types.ts:1]: CourseStatus

File: src/features/course-main/utils/set-label.ts [hunk 11]
```diff
@@ -0,0 +1,24 @@
+import dayjs from 'dayjs';
+import { hasDayInDate } from '.';
+import { Labels } from '@/app/types';
+
+export function setLabel(date: string) {
```
Comment (SpaNb4) [inline src/features/course-main/utils/set-label.ts:5]: getCourseStatus

Comment (SpaNb4) [reply src/features/course-main/utils/set-label.ts:5]: Please specify the return type explicitly

**Review by dzmitry-varabei — APPROVED** [review]

File: src/features/course-main/utils/set-label.ts (hunk 11 above)
Comment (SpaNb4) [reply src/features/course-main/utils/set-label.ts:5]: And I'd a comment explaining the difference between PLANNED, AVAILABLE, and UPCOMING

File: src/app/types/labels.types.ts (hunk 10 above)
Comment (natanchik) [reply src/app/types/labels.types.ts]: Changed

File: src/features/course-main/utils/set-label.ts (hunk 11 above)
Comment (natanchik) [reply src/features/course-main/utils/set-label.ts]: Done

**Review by SpaNb4 — APPROVED** [review]
