### PR TITLE
794-fix: Dark color of icons in footer

### LINKED ISSUE #794: Dark color of icons in footer
## 🐛dark color of icons in footer

If the screen resolution is less than 810 pixels, the light icons aws in the footer are changed to dark ones.
You need to separate the icon types in the code. Add different icon types for the footer and the header. Or find another solution.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to 'https://rs.school/'  
2. Scroll down to footer

## 📸 Screenshots

should be
Image

now
Image

Image
Image

### PR DESCRIPTION
**Pull request by aliakseitokarev**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description
Changed aws icon src depending on MobileViewProps type. A new type CourseIconSrc has been added to protect the code in case the keys of the Сourse type are changed.
Changed the javascript-black logo.
## Related Tickets & Documents

- Related Issue #794 
- Closes #794 

## Screenshots, Recordings

{492F5BEF-5337-42B5-8047-3D3F5994E699}
{47D72183-B283-4F3C-9BAC-E3907E572F86}
## Added/updated tests?

- [ ] 👌 Yes
- [x] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

## Summary by CodeRabbit

- **New Features**
	- Enhanced the mobile view to dynamically render context-specific icons, ensuring that the appropriate header or footer icon is displayed based on the selected view mode.

### CODE REVIEW

File: src/widgets/mobile-view/ui/mobile-view.tsx [hunk 1]
```diff
@@ -23,9 +24,14 @@ type MobileViewProps = {
   onClose?: () => void;
 };
 
+type CourseIconSrc = {
+  [K in keyof Course]: Course[K] extends StaticImageData ? K : never;
+}[keyof Course];
+
```
Comment (Quiddlee) [inline src/widgets/mobile-view/ui/mobile-view.tsx:30]: looks like it'll still work without the type, so let's remove it

Comment (SpaNb4) [reply src/widgets/mobile-view/ui/mobile-view.tsx:30]: @Quiddlee Wouldn't that make the code less type safe?

Comment (Quiddlee) [reply src/widgets/mobile-view/ui/mobile-view.tsx:30]: @SpaNb4 i think it's already safe enough

Screenshot 2025-03-12 at 3 21 21 PM
Screenshot 2025-03-12 at 3 20 51 PM

Comment (SpaNb4) [reply src/widgets/mobile-view/ui/mobile-view.tsx:30]: Agreed, since `icon` prop is typed in `SchoolItem`, we can remove `CourseIconSrc`

Comment (aliakseitokarev) [reply src/widgets/mobile-view/ui/mobile-view.tsx:30]: @Quiddlee and @SpaNb4, I think that, when we change the key in the `Course` type, we immediately get a type error in two places in the code.   

image
image

Without the `CourseIconSrc` type, we only get a type error in one place, as in @Quiddlee's example.

image

But if this double check is not necessary, I will make changes.

**Review by YulikK — APPROVED** [review]

**Review by Quiddlee — APPROVED** [review]

File: src/widgets/mobile-view/ui/mobile-view.tsx (hunk 1 above)
Comment (Quiddlee) [reply src/widgets/mobile-view/ui/mobile-view.tsx]: @aliakseitokarev Got it. Thank you for contributing! Anyway since the error is raised, I'd prefer to keep it as simple as possible

**Review by SpaNb4 — APPROVED** [review]
