### PR TITLE
Fix: dynamic update upcoming courses

### LINKED ISSUE #61: 'Upcoming courses' add dynamic updating
- Refactor component to automatically retrieve information for the block from a list of courses and select the nearest upcoming events. Now we have to manually update the information there.
- Use date-library in this block.
- Add dynamic course counts to the tests.
- Limit the number of courses to 5.

Image

### LINKED ISSUE #198: Delete course with expired date more than 3 weeks from upcoming courses
## 🐛 Describe the Bug

Delete course with expired date more than 3 weeks from upcoming courses in the About Page

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to https://rs.school/community/#about
2. Scroll down to 'Upcoming courses'
3. Observe the error

## 🏁 Expected Behavior

There is no courses with expired date in on "Upcoming courses" section

## 📸 Screenshots

Image

## 🕹️ Device Information

- Windows 10
- Browser: [Chrome]
- Version: [124]

### PR DESCRIPTION
**Pull request by Tedzury**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Related Tickets & Documents

- Related Issue #61 
- Related Issue #198 
- Closes #61
- Closes #198 
- 
## Screenshots, Recordings

Screenshot 2024-05-19 210957

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

File: src/features/home/courses/lib/getCourseIcon.tsx [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+  Angular: <AngularIcon />,
+  'Node.js': <NodeJsIcon />,
+  'AWS Fundamentals': <AwsLogo />,
+  'AWS Cloud Developer': <AwsLogo />,
+};
+
+export type IconsTitle = keyof typeof icons;
+
+export const getCourseIcon = (title: IconsTitle) => {
+  return Object.keys(icons).includes(title) ? icons[title] : null;
```
Comment (Quiddlee) [inline src/features/home/courses/lib/getCourseIcon.tsx:17]:
```tsx
return icons[title];
```

File: src/features/home/courses/lib/getCourseIcon.tsx [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+const icons = {
+  'JS / Front-end Pre-school RU': <HtmlIcon />,
+  'JS / Front-end EN': <JavascriptIcon />,
+  'JS / Front-end RU': <JavascriptIcon />,
+  React: <ReactIcon />,
+  Angular: <AngularIcon />,
+  'Node.js': <NodeJsIcon />,
+  'AWS Fundamentals': <AwsLogo />,
+  'AWS Cloud Developer': <AwsLogo />,
+};
```
Comment (Quiddlee) [inline src/features/home/courses/lib/getCourseIcon.tsx:12]: If we someday wanted to change course title, we will need to keep in mind that we need to change it in 2 different places (in the future the number could be increased). And this can potentially introduce some unexpected bugs.

I suggest to create constant for each course name and use it in the `courses` object keys, `icons` object and if needed to reuse the constants in other places of the app



```tsx
JS_RU_TITLE = 'JS / Front-end Pre-school RU';

const icons = {
  [JS_RU_TITLE]: <HtmlIcon />,
  // ...
};
```

File: src/features/home/courses/ui/CourseCard.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
+type PropsType = {
+  title: string;
+  language: ('en' | 'ru')[];
+  startDate: string;
+  detailsUrl: string;
+  buttonText: string;
+  icon: JSX.Element | null;
+};
```
Comment (Quiddlee) [inline src/features/home/courses/ui/CourseCard.tsx:8]: Some types are duplicated
image
image

File: src/icons/javascript-icon.tsx [hunk 4]
```diff
@@ -0,0 +1,6 @@
+import javascript from '@/assets/icons/js-secondary.webp';
+import Image from '@/features/image';
+
+export const JavascriptIcon = () => {
+  return <Image src={javascript} alt="nodeJS icon" />;
+};
```
Comment (Quiddlee) [inline src/icons/javascript-icon.tsx:6]:
```tsx
alt="JavaScript icon" 
```

File: src/features/home/courses/courses.test.tsx [hunk 5]
```diff
@@ -1,27 +1,70 @@
...
   });
 
-  it('renders course info correctly', () => {
-    const courseElement = screen.getByText('AWS Fundamentals');
-    expect(courseElement).toBeInTheDocument();
-  });
-
   it('renders three course cards', () => {
     const courseCards = screen.getAllByRole('link', { name: 'More arrow_forward' });
     expect(courseCards.length).toBe(5);
```
[the remark this answers is not in the document]
Comment (Tedzury) [reply src/features/home/courses/courses.test.tsx]: What more flexible way do you propose? Because I have a lack of ideas.

File: src/features/home/courses/courses.tsx [hunk 6]
```diff
@@ -1,60 +1,18 @@
...
-    href: buildUrl(`/${ROUTES.COURSES}/${ROUTES.ANGULAR}`),
-    icon: <AngularIcon />,
-  },
-];
-
 export const Courses = () => {
   const size = useWindowSize();
+  const res = useDataByName('courses');
+  const coursesData = formatCoursesData(res?.data as Course[]);
+  const { loading, error } = res;
```
[the remark this answers is not in the document]
Comment (Tedzury) [reply src/features/home/courses/courses.tsx:18]: I suppose this hook was made for a better days in future when we could fetch a real data from some kind of api, so I keep using it for not to refactor this component in future.

File: src/features/home/courses/lib/formatCoursesData.ts [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+    ?.filter((course) => {
+      const startDate = new Date(course.startDate).getTime();
+      return startDate > expirationDate;
+    })
+    .sort((a, b) => {
+      const aDate = new Date(a.startDate).getTime();
+      const bDate = new Date(b.startDate).getTime();
+      return aDate - bDate;
+    })
+    .filter((_, i) => i < 5);
```
[the remark this answers is not in the document]
Comment (Tedzury) [reply src/features/home/courses/lib/formatCoursesData.ts:18]: In the task description it is specified to show only 5 courses at the component.

File: src/features/home/courses/courses.test.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (natanchik) [reply src/features/home/courses/courses.test.tsx]: I mean that the number of courses can be different in different time periods

[the remark this answers is not in the document]
Comment (Tedzury) [reply src/features/home/courses/courses.test.tsx]: I'm using mocked data in the test with 5 items in it, so it always be 5... Or you suggest just to completely remove that test case?

File: src/features/home/courses/lib/formatCoursesData.ts [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+import { Course } from '@/app/types';
+
+const now = dayjs();
+const courseExpirationDate = now.subtract(3, 'week');
+
+export const formatCoursesData = (courses: Course[]) => {
+  return courses
+    ?.filter((course) => {
+      const startDate = dayjs(course.startDate);
+      return startDate > courseExpirationDate;
```
Comment (natanchik) [inline src/features/home/courses/lib/formatCoursesData.ts:11]: There's an `isAfter` query in the date-library.
You can add it in this file
image

File: src/features/home/courses/courses.tsx [hunk 9]
```diff
@@ -1,96 +1,60 @@
...
-    startDate: 'July 1, 2024',
-    href: buildUrl(`/${ROUTES.COURSES}/${ROUTES.ANGULAR}`),
-    icon: <AngularIcon />,
-  },
-];
-
 export const Courses = () => {
   const size = useWindowSize();
+  const laptopScreenBreakPoint = 1440;
+  const tabletScreenBreakPoint = 810;
```
Comment (natanchik) [inline src/features/home/courses/courses.tsx:15]: You can use ready constants
image

File: src/features/home/courses/courses.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (natanchik) [reply src/features/home/courses/courses.tsx:18]: From what I understand it's unlikely anytime soon. I agree that it can be changed. If it requires a big change, a separate issue could be created.

File: src/features/home/courses/lib/formatCoursesData.ts [hunk 10]
```diff
@@ -0,0 +1,19 @@
...
+    })
+    .sort((a, b) => {
+      const aDate = dayjs(a.startDate).valueOf();
+      const bDate = dayjs(b.startDate).valueOf();
+      return aDate - bDate;
```
Comment (natanchik) [inline src/features/home/courses/lib/formatCoursesData.ts:16]: You can use `isAfter` or `isBefore` here too.

File: src/features/home/courses/courses.test.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (natanchik) [reply src/features/home/courses/courses.test.tsx]: I don't mind leaving it as it is.

File: src/features/home/courses/lib/formatCoursesData.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (Quiddlee) [reply src/features/home/courses/lib/formatCoursesData.ts:18]: Can you place `5` in the constant and name it like `MAX_UPCOMING_COURSES` or `NUM_UPCOMING_COURSES_TO_SHOW`. So any other developer can clearly understand what this code is actually doing

And change `filter` to `slice`, so to not create useless loop.

File: src/features/home/courses/courses.tsx (hunk 9 above)
Comment (Tedzury) [reply src/features/home/courses/courses.tsx:15]: Do we really need to install additional libraries just to extract 2 variables from scss file?

Comment (natanchik) [reply src/features/home/courses/courses.tsx:15]: I was thinking the same thing. So let's close this comment

**Review by Quiddlee — APPROVED** [review]
