### PR TITLE
282-feat: Standardize links designation

### LINKED ISSUE #282: Standardize Designation of Internal and External Links Site-Wide
## 🐛 Describe the Bug

An inconsistency has been detected in the presentation of internal and external links on the website. The current situation could lead to user confusion and potentially disrupt the user experience.

As a fix, we need to conduct an inclusive review that encompasses every single link on our site to:

- Identify internal and external links.
- Ensure their appearance aligns with their type (internal or external).

By making the distinction clear through design (color, icons, etc.), we will establish better navigation and clarity, ultimately enhancing the user experience. This will also improve transparency regarding where a link will lead our users prior to them clicking.

## 🔄 Steps to Reproduce
1. Navigate to 'https://rs.school/courses/javascript'
2. Scroll down to 'Communication'
3. Look at external link 'course Discord server'
4. Scroll down to 'What you should know before starting'
5. Click on 'Computer Science.' link
6. Observe the error##

## 🏁 Expected Behavior
All internal and external links across the website should be clearly distinguishable from each other. Users should be able to understand from the link's design whether clicking on it would keep them on our site (internal link) or take them to another website (external link). Consistently marked links aid in navigation and improve overall user experience, providing transparency and clarity.

## 📸 Screenshots

Image

Image

## ✅ Definition of Done (DoD):

The task is done when all internal and external links on the site are distinctly decorated and properly working.

### PR DESCRIPTION
**Pull request by Wystov**
## What type of PR is this? (select all that apply)

- [x] 🍕 Feature

## Description

> [!IMPORTANT]
> 02.09.24 PO approved links design change in accordance to WCAG.
- changed color and added underline of textVariant of CustomLink according to [WCAG](https://www.w3.org/TR/WCAG20-TECHS/F73.html)
- reviewed all links on website and changed them to LinkCustom where applicable.
- LinkCustom opens in new window now if 'external' prop passed to it. also if it's an textVariant of link, it will be marked with symbol indicating external link.
- removed font size from textVariant of link, so it can inherit it from text where it's used.
- changed about.data format to tsx, so we can use directly jsx from it and not just setInnerHtml from string as it worked before.
- set default icons for variants, but they can be still replaced by manually passing icon prop to component
- added 'custom' variant that has no default styling and relies on styles and classes passed as props

## Related Tickets & Documents

- Related Issue #282 
- Closes #282

## Screenshots, Recordings

internal text link
image

external text link
image
image

## Added/updated tests?

- [x] 👌 Yes

## [optional] What gif best describes this PR or how it makes you feel?
IMG_8947

## Summary by CodeRabbit

- **New Features**
	- Introduced a new blue color variable for consistent styling across the application.
	- Enhanced handling of external links with the new `LinkCustom` component, improving user experience and accessibility.

- **Bug Fixes**
	- Simplified link rendering logic by removing unnecessary icon props, ensuring a cleaner user interface.

- **Chores**
	- Streamlined imports and removed unused components to improve code maintainability.

### CODE REVIEW

**Comment by ansivgit** [comment]
There's not our stiles for text links O-O

File: src/shared/ui/link-custom/link-custom.tsx [hunk 1]
```diff
@@ -28,14 +30,22 @@ const linkCustomVariants = cva('', {
...
+  rel: 'noopener noreferrer',
+};
+
 export const LinkCustom = ({
   children,
   href,
   icon = <></>,
   className = '',
-  variant,
+  variant = 'textLink',
```
Comment (alextes90) [inline src/shared/ui/link-custom/link-custom.tsx:43]: no need, as textLink a default variant according to cva

File: src/shared/ui/text-with-link/text-with-link.tsx
Comment (alextes90) [inline src/shared/ui/text-with-link/text-with-link.tsx:1]: I would suggest to rename this component to linkList

File: src/widgets/about/ui/about.tsx [hunk 2]
```diff
@@ -1,6 +1,6 @@
 /* eslint-disable @stylistic/jsx-one-expression-per-line */
 import { InfoGrid } from './info-grid/info-grid';
-import { contentMap } from '../about.data';
+import { contentMap } from '../about.data.tsx';
```
Comment (alextes90) [inline src/widgets/about/ui/about.tsx:3]: Do we need extension here?

File: src/shared/ui/link-custom/link-custom.tsx [hunk 3]
```diff
@@ -28,14 +30,22 @@ const linkCustomVariants = cva('', {
...
+  external = false,
   ...props
 }: LinkCustomProps) => {
+  const iconElement = external && variant === 'textLink' ? <TextLinkIcon /> : icon;
```
Comment (alextes90) [inline src/shared/ui/link-custom/link-custom.tsx:47]: POV: We should either change logic and put all icons here and take them based on variants, or should leave it as previous and provide icons through parents. Why we should make exception for TextLinkIcon. The behavior of component became inconsistent.

File: src/shared/ui/link-custom/link-custom.tsx (hunk 1 above)
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:43]: cva resolves in classnames, but component should know variant earlier to deside if it should render an external indicator icon

Comment (alextes90) [reply src/shared/ui/link-custom/link-custom.tsx:43]: Ok then let remove default variant from cva

Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:42]: done

**Comment by Wystov** [comment]
> There's not our styles for text links O-O

@ansivgit luckily i dont have any disabilities but i still barely can distinguish links from other text in "our styles".  let alone the fact that they're completely failing WCAG criteria (i left a link in pr description, please check it out)

File: src/shared/ui/link-custom/link-custom.tsx (hunk 3 above)
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:46]: Actually i think same, as far as i see all variants except textLink has an arrow icon, so why should we pass it manually if can show it by default. But lets see what others think about it.

File: src/shared/ui/link-custom/link-custom.tsx [hunk 4]
```diff
@@ -25,17 +27,24 @@ const linkCustomVariants = cva('', {
...
```
Comment (SpaNb4) [inline src/shared/ui/link-custom/link-custom.tsx:46]: Please add a test case for this

File: src/widgets/study-path/study-path.test.tsx [hunk 5]
```diff
@@ -23,7 +24,7 @@ vi.mock('@/shared/hooks/use-data-by-name', () => ({ useDataByName: vi.fn().mockI
 
 describe('StudyPath Component', () => {
   it('renders the title and paragraph text correctly for angularPath', () => {
-    render(<StudyPath path="angular" />);
+    render(<MemoryRouter><StudyPath path="angular" /></MemoryRouter>);
```
Comment (SpaNb4) [inline src/widgets/study-path/study-path.test.tsx:27]: nit: for such cases we have the `renderWithRouter` wrapper

File: src/shared/ui/link-custom/link-custom.tsx (hunk 3 above)
Comment (Quiddlee) [reply src/shared/ui/link-custom/link-custom.tsx:46]: i agree that the better option would be to make consistent icons that related to each variant, this will:
1. reduce complexity because component will know exactly what icon should it render by itself based on the variant
2. if we some day want to change the icon on all links we will need to change it only in one place

File: src/widgets/about/about.data.tsx [hunk 6]
```diff
@@ -6,11 +6,12 @@ import personIcon from '@/shared/assets/icons/person-icon.webp';
 import planetIcon from '@/shared/assets/icons/planet.webp';
 import type { CourseNames } from '@/shared/data/communication.data';
 import { DISCORD_LINKS } from '@/shared/data/communication.data';
+import { LinkCustom } from '@/shared/ui/link-custom';
 
 type AboutInfo = {
   id: number;
   title: string;
-  info: string;
+  info: string | JSX.Element;
```
Comment (Quiddlee) [inline src/widgets/about/about.data.tsx:14]: Please prefer to use ReactNode instead of JSX.Element whether it's possible

https://www.totaltypescript.com/jsx-element-vs-react-reactnode

```suggestion
  info: string | ReactNode;
```

Screenshot 2024-08-30 at 22 47 42

File: src/widgets/about/ui/info-grid/info-grid.tsx [hunk 7]
```diff
@@ -6,7 +6,7 @@ interface InfoGridProps {
   items: {
     id: number;
     title: string;
-    info: string;
+    info: string | JSX.Element;
```
Comment (Quiddlee) [inline src/widgets/about/ui/info-grid/info-grid.tsx:9]:
```suggestion
    info: string | ReactNode;
```

**Review by Quiddlee — APPROVED** [review]

File: src/widgets/study-path/study-path.test.tsx (hunk 5 above)
Comment (Wystov) [reply src/widgets/study-path/study-path.test.tsx:27]: thank you for information, changed.

File: src/widgets/about/about.data.tsx (hunk 6 above)
Comment (Wystov) [reply src/widgets/about/about.data.tsx:14]: thanks for article, changed.

File: src/shared/ui/link-custom/link-custom.tsx (hunk 3 above)
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx]: done [37b266c](https://github.com/rolling-scopes/site/pull/467/commits/37b266c31b196f322fd6f3880da0bd6135e30a7e)

File: src/shared/ui/link-custom/link-custom.tsx (hunk 4 above)
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx]: done

**Comment by ansivgit** [comment]
> > There's not our styles for text links O-O
> 
> @ansivgit luckily i dont have any disabilities but i still barely can distinguish links from other text in "our styles". let alone the fact that they're completely failing WCAG criteria (i left a link in pr description, please check it out)

But we have the mockup. And if we would like to change it - this should not be a PRs' decision, it is a designer's decision or, ultimately, a POs' decision. We are actually working on a real project and no one will allow you to just change the color contrary to the mockup, no matter how correct it is. On commercial projects, you get a painful hit on the head for this ))))

image

By the way, at this stage we have a comment from the Lighthouse regarding the text description of the links, but not their color.

File: src/widgets/about/about.data.tsx [hunk 8]
```diff
@@ -66,7 +68,15 @@ const javaScriptEN: () => AboutInfo[] = () => {
     {
       id: 2,
       title: 'Worldwide mentors and trainers',
-      info: 'The Mentors and trainers of our school are front-end and javascript developers from different companies/countries. How to become a <a href="/courses#mentors-wanted">mentor</a>?',
+      info: (
```
Comment (ansivgit) [inline src/widgets/about/about.data.tsx:71]: We're trying to get rid of all the `*.data.tsx` files, and in this case you are creating a new one. It looks like a hack. Obviously, in the future we will have to change this code back.

File: src/shared/ui/link-custom/link-custom.tsx [hunk 9]
```diff
@@ -2,18 +2,20 @@ import { AnchorHTMLAttributes, ReactNode } from 'react';
...
+import { ArrowIcon, TextLinkIcon } from '@/shared/icons';
 
 import styles from './link-custom.module.scss';
 
 export const cx = classNames.bind(styles);
 
-type LinkCustomProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'rel'> &
+type LinkCustomProps = Omit<AnchorHTMLAttributes<HTMLAnchorElement>, 'rel' | 'target'> &
   VariantProps<typeof linkCustomVariants> &
   LinkCustomAdditionalProps;
```
[the remark this answers is not in the document]
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:13]: done

File: src/shared/ui/link-custom/link-custom.tsx [hunk 10]
```diff
@@ -22,20 +24,42 @@ const linkCustomVariants = cva('', {
       rounded: cx('button', 'rounded'),
       primary: cx('button', 'primary'),
       secondary: cx('button', 'secondary'),
+      custom: '', // relies on external classes
```
[the remark this answers is not in the document]
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:27]: done

File: src/shared/icons/arrow-icon.tsx [hunk 11]
```diff
@@ -2,5 +2,13 @@ import arrow from '@/shared/assets/svg/arrow.svg';
 import { Image } from '@/shared/ui/image';
 
 export const ArrowIcon = ({ size = '24px' }: { size?: string }) => {
-  return <Image src={arrow} alt="" height={size} width={size} />;
+  return (
+    <Image
+      src={arrow}
+      alt=""
```
[the remark this answers is not in the document]
Comment (Wystov) [reply src/shared/icons/arrow-icon.tsx:8]: done

File: src/widgets/about/about.data.tsx (hunk 8 above)
Comment (Wystov) [reply src/widgets/about/about.data.tsx:71]: I think it's best possible solution with current data structure, definitely better then using 'dangerouslySetInnerHtml'. And the only way how we can use custom components from data. 
Anyway changing data structure in future will require total rewrite of current components logic.

File: src/shared/ui/link-custom/link-custom.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (ansivgit) [reply src/shared/ui/link-custom/link-custom.tsx]: Please, remove the comment

File: src/widgets/about/about.data.tsx (hunk 8 above)
Comment (ansivgit) [reply src/widgets/about/about.data.tsx]: I think that the logic of `*.data` files should be changed when refactoring widgets. Shared components are the simplest, they should not depend on the type of `*.data` files. I suggest leaving this file unchanged and returning to it when refactoring the widget `About`

File: src/shared/ui/link-custom/link-custom.tsx (hunk 10 above)
[the remark this answers is not in the document]
Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx]: done

File: src/widgets/about/about.data.tsx (hunk 8 above)
Comment (Wystov) [reply src/widgets/about/about.data.tsx]: Without this changes task for links standardization is not fully implemented and no one will care later that custom links should be used here.

Comment (ansivgit) [reply src/widgets/about/about.data.tsx]: We shouldn't use `*.tsx` components in `*.data` files. Now we're discussing the format in which we will store our `*.data` files - it could be `.json` or `.md`, which we will then parse, but it is definitely not `.tsx`

Comment (Quiddlee) [reply src/widgets/about/about.data.tsx]: @ansivgit the pull request is not about the data refactor. I recommend to leave this as it is with components inside and refactor this as a separate milestone after we fully migrate to FSD

Comment (ansivgit) [reply src/widgets/about/about.data.tsx]: @Quiddlee I'm not suggesting refactoring the data, I'm suggesting not changing it at all, instead of creating entities that we'll definitely get rid of

Comment (Quiddlee) [reply src/widgets/about/about.data.tsx]: if we leave it as you suggest we'll have inconsistent links across the site

Screenshot 2024-09-11 at 12 17 54

Comment (ansivgit) [reply src/widgets/about/about.data.tsx]: I am deeply convinced that increasing quantity of "bad" files is wrong and if we can't improve it now, then we should leave everything as is until the `.data` refactoring. We can set styles for the `a` tag and everything will look the same - this is not a problem at all. @SpaNb4 , what do you think?

Comment (SpaNb4) [reply src/widgets/about/about.data.tsx]: Let's leave it as is for now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
run visual now

File: src/shared/ui/link-custom/link-custom.tsx [hunk 12]
```diff
@@ -22,20 +24,42 @@ const linkCustomVariants = cva('', {
       rounded: cx('button', 'rounded'),
       primary: cx('button', 'primary'),
       secondary: cx('button', 'secondary'),
+      withCustomClassName: '',
```
Comment (SpaNb4) [inline src/shared/ui/link-custom/link-custom.tsx:27]: nit: https://github.com/rolling-scopes/site/pull/401#discussion_r1756827044

Comment (Wystov) [reply src/shared/ui/link-custom/link-custom.tsx:27]: done
