### PR TITLE
473-fix: Fsd refactor trainers card

### LINKED ISSUE #473: FSD: Entity trainer
## 📝 Describe the refactoring task

Part of the issue #346 
Trainer entity refactor

## 📍 Code location

`src/entities/trainer`

## ✅ Definition of Done (DoD):

1. create `trainer` folder in `src/entities`.
2. move `src/widgets/trainers/ui/trainers-card` to `src/entities/trainer/ui/trainer-card`.
3. create `trainer-card.module.scss` file in `src/entities/trainer/ui/trainer-card` and move all related to `trainer-card` styles from `trainer.scss`
4. refactor `trainers.scss` file to `modules.scss` and `trainers-card.module.scss` as so: 
  * remove all parent selector `& .card-content` -> `.card-content`. 
  * change all possible values to variables if such exists.
  * rename all classes to be generic e.g `.nodejs-trainer 🙅‍♂️` -> `.trainer 👌`.
  * and everything in your opinion that needs to be refactored
5. move `Trainer` type from `src/widgets/trainers/trainers.types.ts` to `src/entities/trainer/types.ts`
6. create `index.ts` file and re-export `Trainer` type and `TrainerCard` component
7. refactor `TrainerCard` component to utilize HTML5 tags
8. Write unit test for `TrainerCard` component

#### Example of completing all the steps you can find in src/entities/event/event-card

### PR DESCRIPTION
**Pull request by thirdmadman**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Reafctored trainers-card according to the task in issue #473

## Related Tickets & Documents
- Related Issue #473
- Closes #473

## Screenshots, Recordings

no visual changes

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

## [optional] Are there any post deployment tasks we need to perform?
no

## [optional] What gif best describes this PR or how it makes you feel?
Whaaat

## Summary by CodeRabbit

- **Improvements**
	- Updated import paths for the `Trainer` type across multiple files to enhance clarity and maintainability.
	- Introduced a new `TrainerCard` component for displaying trainer information, improving the user interface.
	- Added new styles for the `TrainerCard` component to enhance visual presentation and responsiveness.
	- Renamed and restructured CSS classes for the trainers' UI component to improve organization and maintainability.

- **Tests**
	- Updated mocked trainer data in tests to reflect a new character and background, enhancing relevance for testing scenarios.
	- Modified import statements in test files to align with the new module structure for the `Trainer` type.
	- Enhanced test cases for the `Trainers` component to increase flexibility and maintainability.

### CODE REVIEW

File: src/entities/trainer/ui/trainers-card/trainer-card.tsx [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+type TrainerProps = Trainer;
+
+export const TrainerCard = ({ name, bio, role, photo }: TrainerProps) => {
+  return (
+    <article className={cx('trainer-card')}>
+      <div className={cx('trainer-card__picture')}>
+        <Image src={photo} alt={`${name} ${role}`} />
+      </div>
+      <div className={cx('trainer-card__right')}>
```
Comment (ansivgit) [inline src/entities/trainer/ui/trainers-card/trainer-card.tsx:17]:
```suggestion
      <div className={cx('trainer-card__text/description')}>
```

File: src/shared/__tests__/constants.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@ import nodejsImg1 from '@/shared/assets/mentors/m-shylau.webp';
 import type { Trainer } from '@/entities/trainer/types';
 
 export const MOCKED_IMAGE_PATH = 'mocked-image-path.webp';
-const MOCKED_TRAINER = {
+export const MOCKED_TRAINER = {
   name: 'Maksim Shylau',
```
[the remark this answers is not in the document]
Comment (thirdmadman) [reply src/shared/__tests__/constants.ts]: fixed in https://github.com/rolling-scopes/site/pull/492/commits/5412fadf6dafa719c126a322d5e5a293de18587c

File: src/entities/trainer/ui/trainers-card/trainer-card.tsx (hunk 1 above)
Comment (thirdmadman) [reply src/entities/trainer/ui/trainers-card/trainer-card.tsx]: fixed in https://github.com/rolling-scopes/site/pull/492/commits/0a1775b5be67bfe9689d7da53211f49cdd03e85d

File: src/widgets/trainers/ui/trainers.tsx [hunk 3]
```diff
@@ -28,8 +27,8 @@ export const Trainers = ({ trainers, lang = 'en' }: TrainersProps) => {
   const title = trainersTitle[lang][isMultipleTrainers];
 
   return (
-    <section className="nodejs-trainer container">
-      <div className="nodejs-trainer content gap">
+    <section className="trainers container">
+      <div className="trainers__content content">
```
[the remark this answers is not in the document]
Comment (thirdmadman) [reply src/widgets/trainers/ui/trainers.tsx]: fixed in https://github.com/rolling-scopes/site/pull/492/commits/0a1775b5be67bfe9689d7da53211f49cdd03e85d

File: src/widgets/trainers/ui/trainers.scss [hunk 4]
```diff
@@ -1,88 +1,10 @@
-.nodejs-trainer {
-  & .content {
+.trainers {
```
Comment (Wystov) [inline src/widgets/trainers/ui/trainers.scss:1]: seems like you forgot to convert this one to modules also

Comment (ansivgit) [reply src/widgets/trainers/ui/trainers.scss:1]: I suppose, it's out of scope - we'll change it as part of the widget code refactoring.

**Review by ansivgit — APPROVED** [review]

File: src/widgets/trainers/ui/trainers.scss (hunk 4 above)
Comment (Wystov) [reply src/widgets/trainers/ui/trainers.scss:1]: It's mentioned in issue, pt.4

Comment (ansivgit) [reply src/widgets/trainers/ui/trainers.scss:1]: I asked Bogdan and we decided to remove this part of pt4 as it out of scope

File: dev-data/react-ru.data.ts [hunk 5]
```diff
@@ -1,8 +1,8 @@
+import type { Trainer } from '@/entities/trainer/types';
```
Comment (Quiddlee) [inline dev-data/react-ru.data.ts:1]: violation of the `public api` rule
https://feature-sliced.design/docs/reference/public-api


Screenshot 2024-09-07 at 22 09 21


```suggestion
import type { Trainer } from '@/entities/trainer';
```

File: src/entities/trainer/ui/trainers-card/trainer-card.tsx [hunk 6]
```diff
@@ -0,0 +1,26 @@
+import classNames from 'classnames/bind';
+import { Trainer } from '../../types';
+import { Image } from '@/shared/ui/image';
+
+import styles from './trainer-card.module.scss';
+
+const cx = classNames.bind(styles);
+
+type TrainerProps = Trainer;
```
Comment (Quiddlee) [inline src/entities/trainer/ui/trainers-card/trainer-card.tsx:9]: redundant type

**Review by Quiddlee — CHANGES_REQUESTED** [review]

File: src/entities/trainer/ui/trainers-card/trainer-card.tsx (hunk 6 above)
Comment (thirdmadman) [reply src/entities/trainer/ui/trainers-card/trainer-card.tsx:9]: Is there any way to rewrite it, or you just suggest using Trainer as a type for props?
Im not entirely sure if it's good, because it's just coincidence that the type of etity is completely the same as component props type.

File: dev-data/react-ru.data.ts (hunk 5 above)
Comment (thirdmadman) [reply dev-data/react-ru.data.ts]: fixed in https://github.com/rolling-scopes/site/pull/492/commits/17c6d49e2410fa5452cf36f8633121bed5cb87ba

File: src/entities/trainer/ui/trainers-card/trainer-card.tsx (hunk 6 above)
Comment (Quiddlee) [reply src/entities/trainer/ui/trainers-card/trainer-card.tsx:9]: I don't see any downsides using this type directly as props type. You explicitly will tell that the component accept trainer's type of data

**Review by Quiddlee — APPROVED** [review]

**Review by SpaNb4 — APPROVED** [review]
