### PR TITLE
285-fix: different course days

### LINKED ISSUE #285: Fix the course dates in line throughout the site
## 🐛 Describe the Bug

In the list of all courses, the date for AWS Cloud Developer is unknown. But if we click view details, a page opens that shows the date in the past.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to https://rs.school/
2. Navigate to https://rs.school/courses/#main
3. Compare the dates
4. Observe the errors

## 🏁 Expected Behavior

All courses on all pages have the similar dates

## 📸 Screenshots

Image
Image
Image

## 🕹️ Device Information

Windows 10
Chrome ver 125

## ⚙️ Tech. notes

Design a wrapper around calculating course date logic, in order to reuse it across the website.

### PR DESCRIPTION
**Pull request by Wystov**
## What type of PR is this? (select all that apply)

- [x] 🐛 Bug Fix
- [x] 🧑‍💻 Code Refactor

## Description
Reuse getActualDataList instead of duplicated function with different days const to ensure that course start days are consistent across whole site.

## Related Tickets & Documents

- Related Issue #285 
- Closes #285 

## Added/updated tests?

- [x] 🙅‍♂️ No, because they aren't needed

## Summary by CodeRabbit

- **New Features**
	- Limited the number of courses displayed to a maximum of 5.
	- Updated course fetching logic to filter out stale courses.

- **Tests**
	- Updated tests to ensure the number of course cards rendered does not exceed 5.

### CODE REVIEW

**Review by natanchik — APPROVED** [review]

File: src/widgets/courses-school/ui/courses.tsx [hunk 1]
```diff
@@ -12,11 +13,17 @@ import styles from './courses.module.scss';
 
 const cx = classNames.bind(styles);
 
+const MAX_COURSE_COUNT = 5;
```
Comment (Quiddlee) [inline src/widgets/courses-school/ui/courses.tsx:16]: Please, place constant to `courses-school -> model -> constants.ts`


Accordint to docs

https://feature-sliced.design/docs/guides/issues/desegmented#solution

image

Comment (Wystov) [reply src/widgets/courses-school/ui/courses.tsx:16]: This one used only in this widget, not sure that we need to move it to entities

Comment (Wystov) [reply src/widgets/courses-school/ui/courses.tsx:16]: image

Comment (Quiddlee) [reply src/widgets/courses-school/ui/courses.tsx:16]: Ignore this warn for now, it's a bug

https://github.com/feature-sliced/eslint-config/issues/104

Comment (Wystov) [reply src/widgets/courses-school/ui/courses.tsx:16]: done

**Review by Quiddlee — APPROVED** [review]

File: src/widgets/courses-school/ui/courses.tsx [hunk 2]
```diff
@@ -16,7 +18,11 @@ export const Courses = () => {
   const size = useWindowSize();
   const laptopScreenBreakPoint = 1440;
   const tabletScreenBreakPoint = 810;
-  const coursesData = selectCourses(courses);
+  const coursesData = getActualDataList({
+    dataList: courses,
+    actualDelayInDays: COURSE_STALE_AFTER_DAYS,
+    filtered: true,
+  }) as Course[];
```
Comment (SpaNb4) [inline src/widgets/courses-school/ui/courses.tsx:25]: Let's use `isCourse` type guard here

Comment (Wystov) [reply src/widgets/courses-school/ui/courses.tsx:25]: I'll use it in helper so it will return specified type and no assertions will be in code. But but will make it in issue #400 as @ansivgit asked to separate to small tasks.

**Review by SpaNb4 — APPROVED** [review]
