### PR TITLE
Fix: fix school menu

### LINKED ISSUE #29: CSS issues on https://rs.school/courses/aws-fundamentals
Manjaro Linux, Firefox 123.0.1 (64-bit)

https://rs.school/courses/aws-fundamentals

image

### LINKED ISSUE #51: School menu links

### PR DESCRIPTION
**Pull request by natanchik**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

- School menu links have been moved from the headings to the menu items themselves;
- Changed text from `JS / Front-end course Pre-school` to `JS / Front-end Pre-school`, `Upcoming` to `TBD`;
- Sorted the courses in the menu in the order of recommended completion;
- Refactored code in School menu item and Nav item;
- Removed dropdown menu duplication;
- Updated styles.

## Related Tickets & Documents

- Related Issue #51
- Closes #51 
- Related Issue #29
- Closes #29 

## Screenshots, Recordings

Sorting, text updating, links
Screenshot 2024-04-16 162617

Screenshot 2024-04-16 162605

Adaptive
Screenshot 2024-04-16 163020

Screenshot 2024-04-16 163042

Duplicate deletion
Screenshot 2024-04-16 211007

Screenshot 2024-04-16 223909

Issue #29 Mozilla
Screenshot 2024-04-16 222946

Screenshot 2024-04-16 222956

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

File: src/app/components/school-menu/school-item.tsx [hunk 1]
```diff
@@ -10,28 +10,28 @@ interface SchoolItemProps {
 
 export const SchoolItem = ({ item, index, color }: SchoolItemProps) => {
   return 'description' in item ? (
-    <li key={item.title} className="school-item">
+    <li key={item.title}>
```
Comment (andron13) [inline src/app/components/school-menu/school-item.tsx:13]: There is an obvious duplication of code, I see the creation of `li` twice. Can we try to avoid this? Do we need two different components?

File: src/app/components/school-menu/school-item.tsx [hunk 2]
```diff
@@ -10,28 +10,28 @@ interface SchoolItemProps {
...
-      </div>
+    <li key={item.id} className="school-item">
+      <Link to={item.detailsUrl} className="with-icon">
+        <div className="icon-wrapper">
+          <img src={item.iconSmall} alt={item.title} width={32} height={32} loading="lazy" />
+        </div>
+        <div className="details">
+          <span className={color}>{item.title}</span>
+          <small>
+            {new Date(item.startDate) > new Date() ? `Start ${item.startDate}` : 'Upcoming'}
```
Comment (andron13) [inline src/app/components/school-menu/school-item.tsx:31]: I'm opposed to calculations inside the return statement. I believe that components should display data, not compute it. I suggest calculating a variable in advance.

**Review by andron13 — CHANGES_REQUESTED** [review]
Plz look at the comments, can we improve?

File: src/app/components/school-menu/school-item.tsx (hunk 1 above)
Comment (natanchik) [reply src/app/components/school-menu/school-item.tsx]: Refactored SchoolItem

File: src/app/components/school-menu/school-item.tsx (hunk 2 above)
Comment (natanchik) [reply src/app/components/school-menu/school-item.tsx]: Took the calculations out of the render.

**Review by andron13 — APPROVED** [review]

**Review by ramzes-84 — APPROVED** [review]
