### PR TITLE
765-fix: Fix styles active menu item

### LINKED ISSUE #660: Desktop menu rework
## 📝 Describe the refactoring task

The problem that users are facing is that the menu is not working as expected. For now, the menu will open if you hover over it, and at the same time, you can click on the menu button that can be hovered, and you will be redirected to some page.

This isn't user-friendly.

We want to change the menu to open only if you click on it.

Sub-issue #765

### LINKED ISSUE #765: Menu items active text color
Part of the issue #660 

## 📝 Describe the refactoring task

The problem is that when the item menu is active the text is barely readable

Image

## 🛠️ Suggested improvement

we can make the active state to change color as on the nextjs website

Image

can we fix lighthouse problem with arrows here

Image

Closes: #660

### PR DESCRIPTION
**Pull request by JuliaAnt**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [x] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Rework desktop and mobile menus according to the [new design](https://www.figma.com/design/cpxFbCg3xDdalfW9wjSnmt/RS-Mentorship?node-id=1505-11007&t=TDYeKhaosNFEZmjR-4).

## Related Tickets & Documents

- Related Issue #765
- Related Issue #660 
- Closes #765
- Closes #660 

## Screenshots, Recordings

Before: 

Screenshot 2025-04-12 at 23 03 28

After: 

Screenshot 2025-04-12 at 23 04 21

## Added/updated tests?

- [ ] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [x] 🙋‍♂️ No, because I need help

## [optional] What gif best describes this PR or how it makes you feel?
Feel free to hit me with your best practices :))

so-little-work-i-done

## Summary by CodeRabbit

- **New Features**
  - Added interactive, collapsible navigation menus for desktop and mobile, including new "Support Us" and "Mentors Wanted" sections.
  - Introduced a "small" font size variant for paragraphs and enhanced breadcrumb and logo components with new customization options.
  - Added a custom hook for detecting outside clicks and improved keyboard accessibility in navigation.
  - Introduced a new media query mixin for large laptop viewports.

- **Improvements**
  - Redesigned header and navigation for a more consistent, accessible, and visually appealing experience.
  - Enhanced menu layouts with grid and column support, improved dropdown transitions, and responsive styling.
  - Updated donation options with clearer, distinct labels and icons for buttons and menus.
  - Refined logo sizing for consistent display across devices.
  - Improved dropdown and nav item styling for better focus and hover states.
  - Enhanced mobile menu structure with dynamic accordion-style navigation and state management.
  - Added new navigation menu labels constant for consistent labeling.
  - Improved school menu layout with transition-enabled show/hide states and flexible grid options.
  - Enhanced support section with updated icon rendering and descriptive content.

- **Bug Fixes**
  - Improved accessibility and keyboard navigation throughout navigation components.
  - Fixed test coverage and expectations to align with updated navigation structure and UI.

- **Chores**
  - Refactored and streamlined code for better maintainability, including removal of unused features and improved state management.
  - Updated test mocks and simplified test implementations for header and footer components.

### CODE REVIEW

**Review by YulikK — APPROVED** [review]

**Review by Quiddlee — APPROVED** [review]

**Comment by SpaNb4** [comment]
The arrow's focus state could be improved
image

This isn't due to your changes, but the spacing is inconsistent here
image

**Comment by ansivgit** [comment]
image

**Comment by ansivgit** [comment]
image

For a non-yellow background of the hero-banner, the underline blends in with the image. Also, I think the current page should be highlighted.

File: src/core/base-layout/components/header/nav-item/nav-item.tsx [hunk 1]
```diff
@@ -38,20 +39,23 @@ export const NavItem = ({ label, href, children }: NavItemProps) => {
...
 
-  const handleConfirmKeyPress = (e: KeyboardEvent<HTMLButtonElement>) => {
-    if (e.code === 'Enter' || e.code === 'Space') {
-      e.preventDefault();
-      setDropdownOpen((prev) => !prev);
-    }
-  };
-
   const handleEscKeyPress = (e: KeyboardEvent<HTMLElement>) => {
     if (e.code === 'Escape') {
```
Comment (ansivgit) [inline src/core/base-layout/components/header/nav-item/nav-item.tsx:43]: Let's all keys' codes move to constant like `KEY_CODES = {ESCAPE: 'Escape', .....} You could add it here `src/core/const/index.ts`

File: src/core/base-layout/components/header/dropdown/dropdown-wrapper.module.scss [hunk 2]
```diff
@@ -8,20 +9,23 @@
...
   top: 64px;
-  left: 0;
+  right: 0;
   transform: translateY(-10px);
 
+  display: flex;
+
   width: max-content;
   min-width: 100%;
+  // min-width: calc(100% + var(--header-padding));
```
Comment (YulikK) [inline src/core/base-layout/components/header/dropdown/dropdown-wrapper.module.scss:19]: lets delete it

**Comment by oibioib** [comment]
The breadcrumbs on the site are broken.

**Review by Quiddlee — COMMENTED** [review]
Screenshot 2025-04-17 at 2 58 22 PM
Screenshot 2025-04-17 at 2 49 07 PM
Screenshot 2025-04-17 at 2 48 25 PM
Screenshot 2025-04-17 at 3 04 29 PM


some design inconsistencies, i found so far

1. the top shadow should not be visible
2. the shadow value overall is not matched the design
3. `Support Us` description should't contain hover
4. `Support Us` icons size inconsistent with the design
5. `Support Us` there is a gap missing between columns
6. `Support Us` typography mismatch
7. `Courses` the course text should be vertically aligned to the end
8. `Courses` the gap between rows inconsistent with the design
9. `Courses` the gap between icon and typography inconsistent with the design
10. in the header `RS` icon should be smaller as the design shows

+ bunch of other spacing/typography inconsistencies, please pay attention to these

**Comment by SpaNb4** [comment]
@JuliaAnt, please check the keyboard navigation. It seems like this functionality is no longer working

File: src/widgets/header/ui/nav-item/nav-item.module.scss [hunk 3]
```diff
@@ -49,42 +75,41 @@
     .dropdown-arrow {
       @extend %transition-all;
 
-      margin-left: 10px;
+      cursor: inherit;
+
+      display: flex;
+      align-items: center;
+
+      margin-left: 9px;
```
Comment (YulikK) [inline src/widgets/header/ui/nav-item/nav-item.module.scss:83]: In the project we try not to use margin and also minimize the use of paddings, but this way it will be harder to get into the figma-layout,@ansivgit what do you think?

File: src/widgets/header/ui/nav-item/nav-item.module.scss [hunk 4]
```diff
@@ -49,42 +75,41 @@
...
 
   @include media-hover {
-    &:hover::after {
-      transform: scaleX(1);
-    }
-
-    &:hover .label {
-      color: $color-black;
+    &:hover > .label-bold > .label-content {
+      color: #969fa8;
```
Comment (YulikK) [inline src/widgets/header/ui/nav-item/nav-item.module.scss:112]: lets make a color constant

File: src/widgets/mobile-view/ui/mobile-view.module.scss [hunk 5]
```diff
@@ -1,27 +1,60 @@
...
+    }
+  }
+
+  .menu-content {
+    display: flex;
+    flex-direction: column;
+    flex-grow: 1;
+    gap: 16px;
+    align-items: baseline;
+    justify-content: flex-start;
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-view.module.scss:21]: flex-start - it's default value, so we can delete it

File: src/widgets/mobile-view/ui/mobile-view.module.scss [hunk 6]
```diff
@@ -1,27 +1,60 @@
...
-  font-size: 24px;
+  font-size: 20px;
   font-weight: $font-weight-bold;
+  background: none;
+}
+
+.dark.divider {
+  width: 100%;
+  border: none;
+  border-bottom: 1px solid #d6dce3;
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-view.module.scss:51]: lets make a color constant

File: src/widgets/mobile-view/ui/mobile-view.module.scss [hunk 7]
```diff
@@ -1,27 +1,60 @@
 .mobile-view {
   display: none;
   flex-direction: column;
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-view.module.scss:3]: lets move it to media-tablet-large where we set display: flex;

File: src/widgets/mobile-view/ui/mobile-view.tsx [hunk 8]
```diff
@@ -1,11 +1,24 @@
+'use client';
+
+import { useEffect, useState } from 'react';
 import classNames from 'classnames/bind';
+import { StaticImageData } from 'next/image';
 import Link from 'next/link';
+import { usePathname } from 'next/navigation';
 
+import { MobileNavItem } from './mobile-nav-item/mobile-nav-item';
+import { donateOptionsForNavMenu } from '../../../../dev-data/donate-options.data';
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-view.tsx:10]: update import

File: src/widgets/school-menu/ui/school-item/school-item.module.scss [hunk 9]
```diff
@@ -21,7 +29,7 @@
   &:hover {
     .title {
       &.dark {
-        color: $color-black;
+        color: #969fa8;
```
Comment (YulikK) [inline src/widgets/school-menu/ui/school-item/school-item.module.scss:32]: lets make a color constant

File: src/widgets/school-menu/ui/school-menu/school-menu.module.scss [hunk 10]
```diff
@@ -20,25 +22,69 @@
...
+    opacity: 0;
+  }
+
+  &.visible {
+    @extend %transition-all;
+
+    max-height: 624px;
+    margin-top: 26px;
+    visibility: visible;
+    opacity: 1;
```
Comment (YulikK) [inline src/widgets/school-menu/ui/school-menu/school-menu.module.scss:88]: please use constant for opacity
$opacity-100, $opacity-0

File: src/widgets/school-menu/ui/school-menu/school-menu.tsx [hunk 11]
```diff
@@ -12,13 +12,38 @@ type SchoolMenuProps = PropsWithChildren &
...
+  layout = 'single',
+  isVisible,
+  anchorLinks = false,
+}: SchoolMenuProps) => {
   return (
-    <div className={cx('school-menu')}>
+    <div
+      className={cx('school-menu', {
+        visible: isVisible === true,
+        hidden: isVisible === false,
```
Comment (YulikK) [inline src/widgets/school-menu/ui/school-menu/school-menu.tsx:33]: can we move all properties from .visible to .school-menu and add .hidden if isVisible===true?

File: src/widgets/mobile-view/ui/mobile-view.tsx [hunk 12]
```diff
@@ -20,106 +33,212 @@ const Divider = ({ color }: DividerProps) => <hr className={cx('divider', color)
...
+                title={option.linkLabel}
+                url={option.href}
+                color={color}
+                onClick={onClose}
+              />
+            ))}
+          </SchoolMenu>
+        </div>
+      </div>
     </nav>
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-view.tsx:242]: as a suggestion above, if you're going to split the main header menu into separate blocks, you should split the mobile menu as well. It came out as a very large component

File: src/widgets/mobile-view/ui/mobile-nav-item/mobile-nav-item.tsx [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+    <button onClick={() => onMenuItemClick(title)} className={cx('category-link', color)}>
+      <div className={cx('category-title')}>
+        {icon && (
+          <Image
+            src={icon}
+            alt="Donate-icon"
+            width={20}
+            height={18}
+            aria-hidden="true"
+          />
```
Comment (YulikK) [inline src/widgets/mobile-view/ui/mobile-nav-item/mobile-nav-item.tsx:35]: I understand that we have only one icon now, but still it seems wrong to set in alt donate-icon - if the icon comes in props, maybe then together with the icon to pass the alt? And let's write “little heart” in this icon alt.

**Comment by SpaNb4** [comment]
Noticed some issue with a new course
image

**Comment by gbogdanova** [comment]
I noticed that tapping the logo in the mobile menu doesn't trigger the onClose callback, so the collapsible menu remains open. Maybe we should add onClick={onClose} to the Logo component when it's used in the mobile menu to ensure consistent behavior.

File: src/widgets/header/header.tsx [hunk 14]
```diff
@@ -21,13 +29,13 @@ type HeaderProps = {
...
-type HeaderAccentColor = 'gray' | 'blue' | 'white';
-
 export const Header = ({ courses }: HeaderProps) => {
   const [isMenuOpen, setMenuOpen] = useState(false);
+
   const pathname = usePathname();
-  const headerAccentColor = pathname?.includes(ROUTES.MENTORSHIP) ? 'blue' : 'gray';
-  const [color, setColor] = useState<HeaderAccentColor>(headerAccentColor);
+  const isMentorshipPage = pathname.includes(ROUTES.MENTORSHIP);
+  const iconSrc = isMentorshipPage ? iconBlue : iconYellow;
```
[the remark this answers is not in the document]
Comment (JuliaAnt) [reply src/widgets/header/header.tsx:36]: Do you mean using `logo` instead of `icon` here: `const iconSrc = isMentorshipPage ? iconBlue : iconYellow`? In this case, it's actually a heart icon used for the "Support Us" menu item, not a logo.

File: src/widgets/header/ui/dropdown/dropdown-wrapper.tsx [hunk 15]
```diff
@@ -1,34 +1,25 @@
...
-
 import styles from './dropdown-wrapper.module.scss';
 
 const cx = classNames.bind(styles);
 
 export interface DropdownWrapperProps {
-  onMouseLeave: () => void;
-  onMouseEnter: () => void;
   isOpen: boolean;
+  reverseLayout: boolean;
```
[the remark this answers is not in the document]
Comment (JuliaAnt) [reply src/widgets/header/ui/dropdown/dropdown-wrapper.tsx:10]: We’ve already discussed this earlier :)

File: src/widgets/header/ui/nav-item/nav-item.module.scss [hunk 16]
```diff
@@ -31,16 +46,31 @@
     background-color: $color-black;
   }
 
-  .label {
-    @extend %transition-all;
+  > img {
+    margin-right: 5px;
```
[the remark this answers is not in the document]
Comment (JuliaAnt) [reply src/widgets/header/ui/nav-item/nav-item.module.scss]: I slightly adjusted the styles here and removed this part for consistency)

File: src/widgets/mobile-view/ui/mobile-nav-item/mobile-nav-item.module.scss [hunk 17]
```diff
@@ -0,0 +1,41 @@
...
+  align-items: center;
+}
+
+.dark {
+  color: $color-gray-900;
+}
+
+.light {
+  color: $color-gray-100;
+}
```
[the remark this answers is not in the document]
Comment (JuliaAnt) [reply src/widgets/mobile-view/ui/mobile-nav-item/mobile-nav-item.module.scss:41]: Yup) The font color is different in the header and footer because they have different background colors.

File: src/widgets/mobile-view/ui/mobile-view.module.scss [hunk 18]
```diff
@@ -1,27 +1,59 @@
...
-  justify-content: flex-start;
 
-  width: 100%;
+  .menu-logo {
+    display: flex;
+    align-items: flex-end;
+    min-height: 58px;
+
+    a {
+      margin-bottom: 3px;
```
[the remark this answers is not in the document]
Comment (JuliaAnt) [reply src/widgets/mobile-view/ui/mobile-view.module.scss]: I slightly adjusted the styles here and removed this part for consistency)

File: src/widgets/header/header.tsx (hunk 14 above)
[the remark this answers is not in the document]
Comment (ansivgit) [reply src/widgets/header/header.tsx:36]: You're right!
