### PR TITLE
Fix: layout distortion on zoom out

### LINKED ISSUE #149: Page Layout Distortion on Zoom
Upon zooming in or out on the website, the page layout appears to distort and lose its formatting.

This issue affects the readability and functionality of the site at various zoom levels. 
Reproducing this issue can be done by adjusting the browser zoom level on the website. A resolution for this would likely involve making the layout and design more responsive to scale properly when the page is zoomed. 

Please **investigate and resolve** for a more consistent user experience

Image

### PR DESCRIPTION
**Pull request by ramzes-84**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Now all the blocks are aligned on center on zoom out.

## Related Tickets & Documents

- Related Issue #149 
- Closes #149 

## Screenshots, Recordings

FireShot Capture 034 - Home · The Rolling Scopes School - localhost
FireShot Capture 036 - Home · The Rolling Scopes School - localhost

## [optional] What gif best describes this PR or how it makes you feel?
family-guy-css

## Added/updated tests?

- [ ] 👌 Yes
- [x] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

**Comment by SpaNb4** [comment]
What about these blocks?
image

**Comment by dzmitry-varabei** [comment]
> What about these blocks? image

It's great that you noticed! 🕵️ Thank you!

**Comment by ramzes-84** [comment]
> What about these blocks? image

Fixed

**Comment by ramzes-84** [comment]
FireShot Capture 036 - Home · The Rolling Scopes School - localhost

**Review by SpaNb4 — APPROVED** [review]

File: src/features/base-layout/components/navbar/navbar.tsx [hunk 1]
```diff
@@ -54,34 +54,36 @@ export const Navbar = () => {
 
   return (
     <div className={`navbar ${color}`} data-testid="navigation">
-      <Link to="/" onClick={() => window.scrollTo({ top: 0 })}>
-        <LogoWrapper type="navbar" />
-      </Link>
+      <section className="navbar-content">
```
Comment (SpaNb4) [inline src/features/base-layout/components/navbar/navbar.tsx:57]: Shoudn't it be `nav` tag?

File: src/features/base-layout/components/navbar/navbar.tsx [hunk 2]
```diff
@@ -54,34 +54,36 @@ export const Navbar = () => {
 
   return (
     <div className={`navbar ${color}`} data-testid="navigation">
```
Comment (andron13) [inline src/features/base-layout/components/navbar/navbar.tsx:56]:
```suggestion
    <nav className={`navbar ${color}`} data-testid="navigation">
```

Comment (ramzes-84) [reply src/features/base-layout/components/navbar/navbar.tsx:56]: We don't have `header` yet. 
May be it's better to replace `div` with `header` here, and use `nav` deeper (instead of `menu`)?

Comment (andron13) [reply src/features/base-layout/components/navbar/navbar.tsx:56]: > We don't have `header` yet. May be it's better to replace `div` with `header` here, and use `nav` deeper (instead of `menu`)?

Certainly, your suggestion of placing `<nav>` inside a `<header>` can definitely give better semantic structure to our website. However, for now, our primary focus is on navigation and we're specifically working on that. It's important to note that a `<nav>` element can exist independently of a `<header>`. The current structure doesn't mean that we're excluding the `<header>`, we can always introduce or adjust our layout later as the website's design evolves.

**Comment by ansivgit** [comment]
Navbar and Header have become narrower:
`main` branch:
Screenshot 2024-04-30 at 14 14 26

After your fix:
Screenshot 2024-04-30 at 14 14 13

File: src/features/base-layout/components/navbar/navbar.tsx (hunk 2 above)
Comment (ramzes-84) [reply src/features/base-layout/components/navbar/navbar.tsx]: I completely agree. I have added `nav` tag only.

**Comment by ramzes-84** [comment]
> Navbar and Header have become narrower

I'm not sure it is a problem. The Navbar has max width now (1440px) as any other block on the page. Should it be wider a bit? Which width should it have?
