### PR TITLE
870-fix: Remove invisible black arrows

### LINKED ISSUE #870: Remove invisible black arrows from buttons
## 🐛 Describe the Bug

Currently, the buttons on the page (e.g., the "How to become a mentor" button) contain black arrow icons. The arrows only become visible on hover when the button's background color changes.
We should remove the arrow icons from the buttons.

## 🔄 Steps to Reproduce

Provide the steps to reproduce the behavior:
1. Navigate to the page containing the buttons (e.g., the Mentors Wanted section on the main page).
2. Observe the buttons. Note that the black arrow icon is not visible
3. Hover the mouse cursor over the button
4. Observe that the button background color changes, and the black arrow icon becomes visible

## 📸 Screenshots
default state:
Image

hover state:
Image

### PR DESCRIPTION
**Pull request by gbogdanova**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

- removed invisible black arrows from primary buttons
- remove test that checked for the presence of black arrows on this type of button

## Related Tickets & Documents

- Related Issue #870
- Closes #870

## Screenshots, Recordings
default state:
Screenshot 2025-05-07 at 1 19 48 PM
hover state:
Screenshot 2025-05-07 at 1 20 13 PM

## Added/updated tests?

- [X] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

## [optional] What gif best describes this PR or how it makes you feel?

stimpy-red-button

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated the LinkCustom component so that the arrow icon is no longer displayed for the "primary" variant.
- **Tests**
	- Adjusted tests to confirm the absence of the arrow icon for the "primary" variant and improved test descriptions.

### CODE REVIEW

**Comment by SpaNb4** [comment]
run visual now

**Comment by SpaNb4** [comment]
@gbogdanova Could we also remove `icon-wrapper` from the DOM when no icon is used, to fix text alignment?
image

**Comment by gbogdanova** [comment]
@SpaNb4 I’ve removed the icon-wrapper from this type of button — thanks for pointing it out!

Screenshot 2025-05-08 at 12 02 13 PM

File: src/shared/ui/link-custom/link-custom.tsx
Comment (SpaNb4) [inline src/shared/ui/link-custom/link-custom.tsx:1]: To make this more robust and allow setting custom icons for the primary variant in the future, I would fix it this way:
```
export const LinkCustom = ({
  children,
  href,
  icon,
  className = '',
  variant = 'textLink',
  external = false,
  disabled = false,
  highContrast = false,
  ...props
}: LinkCustomProps) => {
  const resolveIcon = (): ReactNode => {
    switch (true) {
      case external && variant === 'textLink':
        return <TextLinkIcon />;
      case icon !== undefined:
        return icon;
      case variant === 'secondary':
        return <ArrowIcon />;
      case variant === 'rounded':
        return <ArrowIcon />;
      default:
        return 1;
    }
  };

  const IconComponent = resolveIcon();

  return (
    <Link
      className={cx(
        { disabled },
        { highContrast },
        linkCustomVariants({
          variant,
          className,
        }),
      )}
      href={href}
      {...props}
      {...(external && externalLinkAttributes)}
    >
      {children}
      {IconComponent && <span className={cx('icon-wrapper')}>{!disabled && IconComponent}</span>}
    </Link>
  );
};
```
Let me know if you see any issues with this

File: src/shared/ui/link-custom/link-custom.test.tsx [hunk 1]
```diff
@@ -61,18 +61,6 @@ describe('LinkCustom', () => {
...
-    renderWithRouter(
-      <LinkCustom href="/" variant="primary">
-        {label}
-      </LinkCustom>,
-    );
-
-    const icon = screen.getByTestId('arrow-icon');
-
-    expect(icon).toBeInTheDocument();
-  });
```
Comment (SpaNb4) [inline src/shared/ui/link-custom/link-custom.test.tsx:74]: please return this test and refactor it to `it('does not render an icon when variant is primary'`

File: src/shared/ui/link-custom/link-custom.test.tsx [hunk 2]
```diff
@@ -90,7 +78,7 @@ describe('LinkCustom', () => {
     const CustomIcon = () => <div data-testid="custom-icon">custom</div>;
 
     renderWithRouter(
-      <LinkCustom href="/" variant="primary" icon={<CustomIcon />}>
+      <LinkCustom href="/" variant="secondary" icon={<CustomIcon />}>
```
Comment (SpaNb4) [inline src/shared/ui/link-custom/link-custom.test.tsx:81]: please revert this

File: src/shared/ui/link-custom/link-custom.tsx
Comment (gbogdanova) [reply src/shared/ui/link-custom/link-custom.tsx:1]: The default: return 1; doesn't make sense because resolveIcon() will always return a value in this case. I think you meant return null;.

Yes, I agree—this version is more flexible for future customization.

File: src/shared/ui/link-custom/link-custom.test.tsx (hunk 1 above)
Comment (gbogdanova) [reply src/shared/ui/link-custom/link-custom.test.tsx:74]: ok

File: src/shared/ui/link-custom/link-custom.test.tsx (hunk 2 above)
Comment (gbogdanova) [reply src/shared/ui/link-custom/link-custom.test.tsx:81]: ok

File: src/shared/ui/link-custom/link-custom.tsx
Comment (SpaNb4) [reply src/shared/ui/link-custom/link-custom.tsx:1]: Yeah, thanks for pointing that out. I accidentally pasted in the code I was testing, which had `1` instead of `null`

**Review by SpaNb4 — APPROVED** [review]

**Review by YulikK — APPROVED** [review]
