### PR TITLE
fix: update course start dates and links

### LINKED ISSUE #137: Update course start dates and registration links
React
https://wearecommunity.io/events/rs-react-2024q3

Angular
https://wearecommunity.io/events/rs-angular-2024q3

AWS Developer
https://wearecommunity.io/events/aws-cloud-dev-rs2024q2

### PR DESCRIPTION
**Pull request by natanchik**
## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 🚧 Breaking Change
- [ ] 🧑‍💻 Code Refactor
- [ ] 📝 Documentation Update

## Description

Fixed course titles
Updated course start dates and registration links:
- React: https://wearecommunity.io/events/rs-react-2024q3
- Angular: https://wearecommunity.io/events/rs-angular-2024q3
- AWS Developer : https://wearecommunity.io/events/aws-cloud-dev-rs2024q2

## Related Tickets & Documents

- Related Issue #137
- Closes #137

## Screenshots, Recordings

Screenshot 2024-04-25 142820
Screenshot 2024-04-25 142846

## Added/updated tests?

- [x] 👌 Yes
- [ ] 🙅‍♂️ No, because they aren't needed
- [ ] 🙋‍♂️ No, because I need help

### CODE REVIEW

File: src/features/home/courses/courses.tsx [hunk 1]
```diff
@@ -23,18 +23,32 @@ const courses: CourseProps[] = [
     icon: <AwsLogo />,
   },
   {
-    title: 'JS / Front-end. Pre-school',
+    title: 'AWS Cloud Developer',
```
Comment (ansivgit) [inline src/features/home/courses/courses.tsx:26]: I suppose, we need one data-source for all courses components (e.g. `courses.data.ts`), and we have to remove all data from components and tests.

File: src/app/services/data/courses.data.ts [hunk 2]
```diff
@@ -64,33 +64,33 @@ export const courses: Course[] = [
...
   {
     id: '4',
-    title: 'React JS course',
+    title: 'React',
     iconSrc: react,
     iconSmall: reactSmall,
     secondaryIcon: reactSecondary,
-    startDate: 'Jul, 2024',
-    language: ['ru', 'en'],
+    startDate: 'Jul 1, 2024',
```
Comment (ansivgit) [inline src/app/services/data/courses.data.ts:71]: We're talking about date-libraries. I supposed we'll use it here - you have one data-source with date in `numeric` format and then we format it as we need depending on the component

File: src/features/course-main/course-main.tsx [hunk 3]
```diff
@@ -37,7 +37,7 @@ export const CourseMain = ({ courseName, type }: CourseMainProps) => {
         </div>
         <div className="info">
           <SectionLabel label={label} />
-          <Title text={altTitle || title} />
+          <Title text={`${altTitle || title} Course`} />
```
Comment (ansivgit) [inline src/features/course-main/course-main.tsx:40]: I think it will be better to remove all 'hardcoding' from the components

File: src/features/home/courses/courses.scss [hunk 4]
```diff
@@ -47,71 +47,52 @@
...
 
         display: flex;
-        flex-direction: row;
         align-items: center;
         justify-content: space-between;
 
         width: 100%;
         margin-top: 24px;
 
         & .icon-container {
```
Comment (ansivgit) [inline src/features/home/courses/courses.scss:56]:
```suggestion
        .icon-container {
```

File: src/features/home/courses/courses.scss [hunk 5]
```diff
@@ -47,71 +47,52 @@
...
-          position: relative;
+          @include media-mobile-landscape {
+            gap: 5px;
```
Comment (ansivgit) [inline src/features/home/courses/courses.scss:58]: Please, use `rem` here and below

File: src/features/home/courses/courses.scss [hunk 6]
```diff
@@ -47,71 +47,52 @@
         }
 
         display: flex;
```
Comment (ansivgit) [inline src/features/home/courses/courses.scss:49]: I thought we decided to use CSS-modules. Or will we still thinking about to use Tailwind CSS?

File: src/features/home/courses/courses.scss [hunk 7]
```diff
@@ -47,71 +47,52 @@
...
         width: 100%;
         margin-top: 24px;
 
         & .icon-container {
-          position: relative;
+          @include media-mobile-landscape {
+            gap: 5px;
+            padding: 10px;
+
+            & .icon-lang {
```
Comment (ansivgit) [inline src/features/home/courses/courses.scss:61]:
```suggestion
            .icon-lang {
```
Here and in other places

File: src/features/home/courses/courses.scss [hunk 8]
```diff
@@ -47,71 +47,52 @@
...
+              color: $color-secondary-gray600;
+            }
+          }
 
-          overflow: visible;
           display: flex;
-          flex-flow: row nowrap;
-          flex-shrink: 0;
+          flex-wrap: wrap;
           gap: 0;
```
Comment (ansivgit) [inline src/features/home/courses/courses.scss:70]: Why do you need it here?

File: src/features/home/courses/courses.tsx (hunk 1 above)
Comment (natanchik) [reply src/features/home/courses/courses.tsx:26]: Yes, these changes are planned as part of the 61 issue: https://github.com/rolling-scopes/site/issues/61

File: src/app/services/data/courses.data.ts (hunk 2 above)
Comment (natanchik) [reply src/app/services/data/courses.data.ts:71]: In issue https://github.com/rolling-scopes/site/issues/61, I plan to spell out the logic for working with dates and add a library to that block there. I can add this point to the issue.

File: src/features/home/courses/courses.scss (hunk 8 above)
Comment (natanchik) [reply src/features/home/courses/courses.scss:70]: Oh, I needed that in one of the language placement options)

File: src/features/home/courses/courses.test.tsx [hunk 9]
```diff
@@ -18,27 +18,27 @@ describe('Courses', () => {
...
   it('renders course info correctly', () => {
-    const courseElement = screen.getByText('AWS Fundamentals (EN)');
+    const courseElement = screen.getByText('AWS Fundamentals');
     expect(courseElement).toBeInTheDocument();
   });
 
   it('renders three course cards', () => {
     const courseCards = screen.getAllByRole('link', { name: 'More arrow_forward' });
-    expect(courseCards.length).toBe(3);
+    expect(courseCards.length).toBe(5);
```
[the remark this answers is not in the document]
Comment (natanchik) [reply src/features/home/courses/courses.test.tsx:27]: Added these items to the issue https://github.com/rolling-scopes/site/issues/61

File: src/features/home/courses/courses.scss (hunk 5 above)
Comment (natanchik) [reply src/features/home/courses/courses.scss]: Removed this unused code

File: src/features/home/courses/courses.scss (hunk 4 above)
Comment (natanchik) [reply src/features/home/courses/courses.scss:56]: Done

File: src/features/home/courses/courses.scss (hunk 6 above)
Comment (natanchik) [reply src/features/home/courses/courses.scss:49]: As far as I'm concerned, the final decision hasn't been made yet.

File: src/features/home/courses/courses.scss (hunk 7 above)
Comment (natanchik) [reply src/features/home/courses/courses.scss]: Done

File: src/app/services/data/courses.data.ts [hunk 10]
```diff
@@ -36,7 +36,7 @@ export const courses: Course[] = [
   },
   {
     id: '2',
-    title: 'JS / Front-end course EN',
+    title: 'JS / Front-end EN',
```
[the remark this answers is not in the document]
Comment (natanchik) [reply src/app/services/data/courses.data.ts:39]: I think it would be a good idea to refactor this component at all. I can see what can be done when doing this task https://github.com/rolling-scopes/site/issues/143

File: src/features/course-main/course-main.tsx (hunk 3 above)
Comment (natanchik) [reply src/features/course-main/course-main.tsx:40]: I think it would be a good idea to refactor these components. I can see what can be done when doing this task https://github.com/rolling-scopes/site/issues/143

File: src/app/services/data/courses.data.ts (hunk 2 above)
Comment (ansivgit) [reply src/app/services/data/courses.data.ts:71]: I suppose, libraries don't relevant to #61 task. You can add library in this PR to foment PR 61 task instead

File: src/features/course-main/course-main.tsx (hunk 3 above)
Comment (ansivgit) [reply src/features/course-main/course-main.tsx:40]: It's doesn't relevant #143  task. You can create an issue for refactoring, but it is not good practice - write `wrong` code, merge it and then refactor it for `good` code

File: src/features/home/courses/courses.scss (hunk 6 above)
Comment (ansivgit) [reply src/features/home/courses/courses.scss:49]: I suppose we have to do our best for now (specially it takes only 1-2 minutes of your time), because at the moment we don't know the structure of our project in the future

File: src/features/home/courses/courses.tsx (hunk 1 above)
Comment (ansivgit) [reply src/features/home/courses/courses.tsx:26]: I suppose, it doesn't quite fit the task #61 . You can change in this PR to foment PR 61 task instead

File: src/features/home/courses/courses.scss (hunk 5 above)
Comment (ansivgit) [reply src/features/home/courses/courses.scss]: But you still leave `px` in this file
